### ISSUE TITLE
anti-meridian bug

### ISSUE THREAD

**Issue by barf** [daniluk4000/vatsim-radar#263]
### Your Vatsim CID

1245742

### Radar version

0.4.3

### Describe your issue

This map is unable to be centered on the anti-meridian, making Pacific flights disappear and reappear at the other side of the world map.

### Reproduction steps

1. Pan the map to the anti-meridian (180 longitude)

### Platform

Firefox on Ubuntu GNU/Linux 22.04

### Additional info

I think this is the same as the simaware map issue # 65 https://github.com/maiuswong/simaware-express/issues/65 

The patch is available for Leaflet for 7 years now:
https://github.com/briannaAndCo/Leaflet.Antimeridian

The Leaflet.Geodesic project also has worked around this: 
https://github.com/henrythasler/Leaflet.Geodesic

### Validation

- [X] I have searched for other issues and didn't found any alike
- [X] I have also checked roadmap, and this is not planned

**Comment by barf** [comment]
It may help illustrate with a screenshot, this is likely to result in other bugs rendering things, like this line that wraps the globe when selecting a flight that crossed the anti-meridian.
![image](https://github.com/user-attachments/assets/c0030c38-5b88-4412-b94c-d66bef352aae)

**Comment by daniluk4000** [comment]
We are not using Leaflet. It's easy to render flights twice, but I can't say the same for controllers, overlays, popups, and more.

For now, this is wontfix. Bug with this long line will be fixed in 0.4.4.

**Comment by barf** [comment]
Thank you, I hope it can be looked at, for now flying in the Pacific not possible with this!

**Comment by daniluk4000** [comment]
> Thank you, I hope it can be looked at, for now flying in the Pacific not possible with this!

Maybe some day. Hardest part is to render controllers, etc. Maybe it will be even easier to just add 3d world map then to do duplicate rendering like VatSpy does already to do this feature

**Comment by barf** [comment]
Thank you for you work! The older vattastic map can be panned completely around too. It would help a lot when flying across the Pacific!

**Comment by barf** [comment]
Hi is there any update on this?

It's a show-stopping bug or regression from existing tools like VATspy, and I see new features on the roadmap before blocking issues like this.

**Comment by barf** [comment]
To reproduce simply pan the map to New Zealand. Traffic is not shown over the anti-meridian.
![image](https://github.com/user-attachments/assets/016293c1-9e94-4d41-b2ca-5d3e9f783313)

**Comment by coldnebo** [comment]
I ran into this issue last week -- I hadn't noticed that the map had "two" asias, so I thought maybe asian traffic wasn't shown because CTP was overloading the servers. But I always scroll to the left out of habit. Today I scrolled to the right and not only did I see the traffic, I saw ATC, etc.  Here's what it looks like with the browser scale reduced so that you can see both sides of the repeated worldmap texture:

![vatsim-radar-bug](https://github.com/user-attachments/assets/f72ab7e5-3e94-4db3-9d54-a5d73d55dad9)

As a dev I understand the technical reason behind the wont-fix label. duplicating is probably the easiest thing, but could be a performance killer. 

However, this image shows the user experience isn't great either. Look at the two aircraft just east of New Zealand. You can only see them in the left side, not in the right scroll. But you can see NZ control is up in the right side.  This means users have to know to switch sides at that mysterious unmarked point.

What I would suggest is somehow visually indicating this hidden "border" where the telemetry will be shown vs not shown. The simplest thing would be to disable the texture repeat so that the user can clearly see the area of update. Another more pleasing option might be to apply a slight grey-out overlay to anything outside the update area. 

This way you don't have to worry about the performance of the solution.

**Comment by coldnebo** [comment]
@barf I did look at the Leaflet.Geodesic demo you linked, but it doesn't do the same thing. it addresses drawing a geodesic across map boundaries, but it doesn't wrap the world map texture. 

In the other demo that does wrap the world map texture there appears to be infinite scroll left and right, however the marker CSS popups are not duplicated, which means that anything not a texture is lost in the infinite repeats left and right.

**Comment by daniluk4000** [comment]
Yeah it's mostly the popups. All vector staff is automatically duplicated. I can duplicate aircraft right now. 

But for popups - no solutions I know about. Adding some sort of a layer to non-working "worlds" seems to be a solution.

**Comment by barf** [comment]
I live in New Zealand, it's not really an option to use this map for flights in the Pacific area due to this bug. The older VATTASTIC also shows a continuous world map.

Thanks again for looking into this! That pull request was the most I could find searching GitHub projects for the issue @coldnebo sorry if I sent you in the wrong direction!

**Comment by barf** [comment]
Is there any update on this? It's still not possible to navigate around the Pacific on this map, so I am using other VATSIM maps
